version: '2'

services:
  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    env_file:
    - ./.env.dist
    volumes:
      - ./duckdns:/config #optional
    restart: unless-stopped
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
      - 8080:8080
#    network_mode: host
    env_file:
      - ./.env.dist
    networks:
      - back
      - front
    labels:
      - traefik.enable=true
      - traefik.backend=traefik
      - traefik.port=8080
      - traefik.docker.network=front
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme/acme.json:/acme.json
      - ./traefik/log:/var/log/traefik
    container_name: traefik
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi3-homeassistant:latest
    ports:
      - 8123:8123
    depends_on:
      - grafana
      - mosquitto
    devices:
      - /dev/ttyACM0:/dev/ttyACM0:rwm
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
    volumes:
      - ./homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
#    environment:
#      - TZ=Europe/Paris
#    network_mode: host
    networks:
      front:
      back:
    labels:
      - traefik.enable=true
      - traefik.port=8123
      - traefik.frontend.entryPoints=https
      - traefik.docker.network=front
      - traefik.frontend.rule=Host:hass.domain.com
      - traefik.backend.entryPoints=http
      - traefik.backend.rule=Host:hass.domain.local
    restart: unless-stopped
  node-red:
    container_name: node-red
    image: nodered/node-red-docker:rpi
    networks:
      back:
    ports:
      - 1880:1880
    volumes:
      - ./node-red:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: "no" # because the exit code(s) are wrong
    depends_on:
      - mosquitto
      - homeassistant
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    networks:
      - back
      - front
    ports:
      - 1883:1883
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto:/mosquitto/config:ro
      - ./mosquitto:/mosquitto/data
  influxdb:
    image: influxdb:latest
    networks:
      - back
    ports:
      - '8086:8086'
    volumes:
      - influxdb-volume:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    user: "104"
    networks:
      back:
    ports:
      - '3000:3000'
    volumes:
      - grafana-volume:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  grafana-volume:
  influxdb-volume:

networks:
  front: ~
  back: ~
